### ISSUE TITLE
v4.2.12

### ISSUE THREAD

**Issue by lonix1** [m0wer/docker-taiga#1]
How do we upgrade to latest?

**Comment by m0wer** [comment]
I periodically check the releases from <https://github.com/taigaio/taiga-back/> and then upgrade the *Dockerfile* and *README.md*. Feel free to ping me if you need it faster @lonix1 .

**Comment by lonix1** [comment]
No worries... I made some edits myself so I'm on the latest version. But your dockerfile did 99% of the work for me, so thanks!

It's so frustrating that the other docker-taiga stuff is outdated or unsupported, I was very pleased to stumble on this repo, saved me lots of time!

**Comment by m0wer** [comment]
That's great! Feel free to open a PR if you feel like it.

I had the same frustrating experience :( That's why I forked from <https://github.com/fanningert/docker-taiga> and kept going from there.
