### ISSUE TITLE
[Question] Change default admin credentials

### ISSUE THREAD

**Issue by lonix1** [m0wer/docker-taiga#4]
Quick question... would you know how to change the default credentials for

- admin user (default is admin:123123)
- default admin django user (accessible via `localhost:8000/admin/`)

Ideally these should be in the script as environment variables.

I haven't found a way to do this, I was wondering if you encountered the same problem?

(Of course, the easy solution is to start the container and immediately change the credentials)

**Comment by m0wer** [comment]
The default user password is set in <https://github.com/taigaio/taiga-back/blob/1b0b879843ce8fc5eaf8343de8d49e46073d90c2/taiga/projects/management/commands/sample_data.py#L615>, maybe if that line had an optional environment variable and a fallback to the default value we could do the trick.

**Comment by lonix1** [comment]
Yeah looks like this isn't possible right now! Something to consider in the future :smile:
